name: trigger
# https://stackoverflow.com/questions/77021205/how-to-flow-inputs-from-workflow-run

on:
  workflow_dispatch:
    inputs:
      limit:
        type: number
        required: true

jobs:
  test:
    name: test-on trigger
    runs-on: ubuntu-latest

    steps:
      - name: limit
        run: echo  ${{ inputs.limit }}