name: SO 45 Matrix
# https://stackoverflow.com/questions/77002736/extract-matrix-step-output-for-each-element-in-a-github-reusable-workflow

on: 
    workflow_dispatch


jobs:
    testa:
      strategy:
        matrix:
          package: ${{ fromJSON('["A", "B", "C"]') }}
      runs-on: ubuntu-latest
      steps:
      # output what you want, the output of package B will be available in needs for furture jobs
      - run: echo "MyKey=${{ matrix.package }}" > $GITHUB_OUTPUT
        id: mystep
      - id: list_dirs
        run: echo "::set-output name=matrix::${{ matrix.package }}"
      outputs:
        B: ${{ steps.mystep.outputs.mykey || '' }}
    testb:
      runs-on: ubuntu-latest
      needs: testa
      steps:
      - run: ${{ tojson(needs) }}
        shell: cat {0}