name: SO 46 Github CLI
# https://stackoverflow.com/questions/77002009/how-can-i-replace-a-globally-defined-repository-variable-in-github-from-within-a

on: 
    workflow_dispatch

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            gh variable list
            gh variable set TEST_VAR --body "Set from workflow"
            gh variable list
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_PAT }}
