name: so-040-timeout

#https://stackoverflow.com/questions/76669354/github-action-how-to-run-a-job-after-another-job-timeoout

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          while true; do echo 1; sleep 1; done

  # cancel:
  #   if: ${{ needs.build.result == 'failure' }}
  #   #if: ${{ always() }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: cancel
  #       run: |
  #         echo "cancel"
  #         echo "${{ needs.build.result }}"


  cancel:
    if: ${{ failure() }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: cancel
        run: |
          echo "cancel"
          echo "${{ needs.build.result }}"