name: Secrets

# https://stackoverflow.com/questions/77103393/how-to-access-the-secrets-on-github-actions

on:
    workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
        GOOGLE_API_KEY: ${{ secrets.SuperSecret }}

    steps:
        - name: display
          run: |
            echo "$GOOGLE_API_KEY" |  awk '$1=$1' FS= OFS=" "

            touch .env
            echo GOOGLE_API_KEY = $GOOGLE_API_KEY >> .env

            cat .env | awk '$1=$1' FS= OFS=" "