name: SO 47 pipe
# https://stackoverflow.com/questions/77017574/pipes-not-working-in-shell-steps-of-github-actions

on: 
    workflow_dispatch

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cancel
        run: |
            echo "cancel"
            cat README.md
            ls /home/runner/work/_temp/
            cat /home/runner/work/_temp/*.sh
      - name: just use a pipe
        shell: bash
        run: |
            env | grep "GITHUB_RETENTION_DAYS"
            ls -al
            result2="$(ls -al | grep git)"
            echo "$result2"
            echo $result2
            result=`cat README.md | grep "test"`
            echo $result

      - name: just use a pipe
        shell: bash
        run: |
            ls -al | grep git