name: Secrets

# https://stackoverflow.com/questions/77103393/how-to-access-the-secrets-on-github-actions

on:
  workflow_call:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
        GOOGLE_API_KEY: ${{ secrets.SuperSecret }}

    steps:
        - name: display
          run: |
            echo "$GOOGLE_API_KEY" |  awk '$1=$1' FS= OFS=" "